Repository lodash/lodash, pull requests merged in 2019-03, with the labels that each got.

#4233 Fix _.maxBy and _.minBy
  maxBy.js
  minBy.js
Labels: bug

#4230 Simplifies toNumber and add tests
  lodash.js
  test/test.js
Labels: enhancement

#4239 tweak _.clone/_.cloneDeep docs
  clone.js
  cloneDeep.js
Labels: documentation

#4244 mergeWith: stack passed to customizer should always be defined
  lodash.js
  test/test.js
Labels: enhancement
