Repository lodash/lodash, pull requests merged in 2019-08, with the labels that each got.

#4404 Add missing isTypedArray import to baseClone
  .internal/baseClone.js
Labels: bug

#4405 Do not use property shorthand in countBy documentation
  countBy.js
Labels: documentation

#4409 Add missing isObject import to isIterateeCall
  .internal/isIterateeCall.js
Labels: bug

#4410 Coerce indexOf fromIndex parameter to integer using toInteger
  indexOf.js
Labels: bug

#4411 Enable indexOf tests
  test/findIndex-and-indexOf.js
  test/indexOf.test.js
Labels: bug

#4412 Coerce drop and dropRight n param using toInteger
  drop.js
  dropRight.js
  test/drop.test.js
  test/dropRight.test.js
Labels: bug

#4413 Coerce to integer and set default value for chunk size parameter
  chunk.js
  test/chunk.test.js
Labels: bug

#4416 lint files
  .internal/baseOrderBy.js
  .internal/createAssigner.js
  .internal/getSymbols.js
  .internal/getSymbolsIn.js
  .internal/getTag.js
  .internal/isIterateeCall.js
  .internal/root.js
  debounce.js
  findLast.js
  throttle.js
Labels: bug

#4417 Implement asciiWords and unicodeWords using String.match instead of binding RegExp.exec
  .internal/unicodeWords.js
  test/words.test.js
  words.js
Labels: bug

#4430 Ensure after n parameter is coerced from NaN to 0
  after.js
  test/after.js
  test/after.test.js
Labels: bug

#4429 merge: copy function values independent of source index
  .internal/baseMergeDeep.js
  test/merge.test.js
  test/utils.js
Labels: bug

#4431 Flatten at paths parameter
  at.js
  test/at.test.js
Labels: bug

#4418 Enable create tests and adapt it for the new primitive prototype behavior
  test/create.test.js
Labels: enhancement

#4432 Ensure escapeRegExp returns an empty string when passing falsy values
  escapeRegExp.js
  test/escapeRegExp.test.js
Labels: bug

#4436 Enable case methods tests
  test/camelCase.test.js
  test/case-methods.test.js
  test/lowerCase.test.js
  test/startCase.test.js
  test/upperCase.test.js
Labels: enhancement

#4440 Coerce findLastIndex and lastIndexOf fromIndex parameter to integer
  findLastIndex.js
  lastIndexOf.js
  test/findLast.test.js
  test/findLastIndex-and-lastIndexOf.test.js
Labels: bug

#4441 Simplify toString
  test/toString.test.js
  toString.js
Labels: enhancement

#4442 Fix string methods to handle empty values
  .internal/createCaseFirst.js
  camelCase.js
  capitalize.js
  escape.js
  kebabCase.js
  lowerCase.js
  pad.js
  padEnd.js
  padStart.js
  snakeCase.js
  test/Strings-category-methods.js
  test/Strings-category-methods.test.js
  trim.js
  trimEnd.js
  trimStart.js
  truncate.js
  unescape.js
  upperCase.js
Labels: bug

#4445 Fix flow and flowRight parameter handling
  flow.js
  flowRight.js
  test/flow-methods.js
  test/flow-methods.test.js
Labels: bug

#4450 Prevent ReDos in words
  words.js
Labels: bug

#4453 add order by behaviour with array similar to get method
  .internal/baseOrderBy.js
  test/orderBy.js
Labels: bug
