Repository lodash/lodash, pull requests merged in 2019-02, with the labels that each got.

#4139 cancel old timer for issue 4138
  lodash.js
Labels: bug

#4187 Cancel old timer, editing pr #4139
  debounce.js
Labels: enhancement

#4199 Remove --save option as it isn't required anymore
  README.md
Labels: documentation
