Repository lodash/lodash, pull requests merged in 2019-10, with the labels that each got.

#4490 Fix vulnerabilities in npm packages
  package-lock.json
  package.json
Labels: enhancement

#4497 (4.17) Short circuit sortedIndexBy methods for empty arrays
  lodash.js
  test/test.js
Labels: enhancement

#4513 Ensure `orderBy` will accept iteratee path arrays #4438
  lodash.js
  test/test.js
Labels: bug

#4514 Document matches* shorthands for over* methods (#4510)
  lodash.js
Labels: documentation

#4515 Fix lodash.isEqual for circular references #4320
  lodash.js
  test/test.js
Labels: bug
