Repository lodash/lodash, pull requests merged in 2019-04, with the labels that each got.

#4259 Fix findLast missing dependency
  findLast.js
Labels: bug

#4272 Round Infinity with a precision argument returns Infinity
  lodash.js
  test/test.js
Labels: enhancement

#4285 Minor doc format
  times.js
Labels: documentation
